{
  "openapi": "3.0.0",
  "info": {
    "title": "API de Manipulação de Alunos",
    "description": "API para criar, listar, buscar, atualizar e deletar alunos",
    "version": "1.0.0"
  },
  "paths": {
    "/alunos": {
      "post": {
        "summary": "Cria um novo aluno",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Aluno"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Aluno criado com sucesso",
            "content": {
              "application/json": {
                "example": {
                  "id": 1,
                  "nome": "Elias",
                  "idade": 18,
                  "nota_primeiro_semestre": 9.5,
                  "nota_segundo_semestre": 8.5,
                  "nome_professor": "Professor XYZ",
                  "numero_sala": 101
                }
              }
            }
          },
          "400": {
            "description": "Dados inválidos"
          }
        }
      },
      "get": {
        "summary": "Lista todos os alunos",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "example": [
                  {
                    "id": 1,
                    "nome": "elias",
                    "idade": 18,
                    "nota_primeiro_semestre": 9.5,
                    "nota_segundo_semestre": 8.5,
                    "nome_professor": "joao",
                    "numero_sala": 101
                  }
                ]
              }
            }
          },
          "500": {
            "description": "Erro ao buscar alunos"
          }
        }
      }
    },
    "/alunos/{id}": {
      "get": {
        "summary": "Obtém um aluno por ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "ID do aluno",
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Aluno encontrado",
            "content": {
              "application/json": {
                "example": {
                  "id": 1,
                  "nome": "Nome do Aluno",
                  "idade": 18,
                  "nota_primeiro_semestre": 9.5,
                  "nota_segundo_semestre": 8.5,
                  "nome_professor": "Professor XYZ",
                  "numero_sala": 101
                }
              }
            }
          },
          "404": {
            "description": "Aluno não encontrado"
          },
          "500": {
            "description": "Erro ao buscar aluno"
          }
        }
      },
      "put": {
        "summary": "Atualiza um aluno por ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "ID do aluno",
            "schema": {
              "type": "integer"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Aluno"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Aluno atualizado com sucesso"
          },
          "404": {
            "description": "Aluno não encontrado"
          },
          "400": {
            "description": "Dados inválidos"
          },
          "500": {
            "description": "Erro ao atualizar aluno"
          }
        }
      },
      "delete": {
        "summary": "Deleta um aluno por ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "ID do aluno",
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Aluno deletado com sucesso"
          },
          "404": {
            "description": "Aluno não encontrado"
          },
          "500": {
            "description": "Erro ao deletar aluno"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Aluno": {
        "type": "object",
        "properties": {
          "nome": {
            "type": "string"
          },
          "idade": {
            "type": "integer"
          },
          "nota_primeiro_semestre": {
            "type": "number"
          },
          "nota_segundo_semestre": {
            "type": "number"
          },
          "nome_professor": {
            "type": "string"
          },
          "numero_sala": {
            "type": "integer"
          }
        }
      }
    }
  }
}
